function d = partial_derivative2(u, v)
  d = 4 / ...
  ((1 - norm(v)^2) * sqrt((1 + 2 / ((1 - norm(u)^2)*(1 - norm(v)^2)) * norm(u - v))^2 - 1)) * ...
  (((norm(v)^2 - 2 * (u' * v) + 1) * u) / (1 - norm(u)^2)^2 - v / (1 - norm(u)^2));
end
